// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dinamicasAgile.Banco;

namespace dinamicasAgile.Migrations
{
    [DbContext(typeof(DinamicaContext))]
    [Migration("20181023185844_EnumTipos")]
    partial class EnumTipos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dinamicasAgile.Models.Dinamica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Arquivada");

                    b.Property<int>("FluxoId");

                    b.Property<int>("ResumoId");

                    b.HasKey("Id");

                    b.HasIndex("FluxoId");

                    b.HasIndex("ResumoId");

                    b.ToTable("Dinamicas");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Exemplo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avaliacao")
                        .IsRequired();

                    b.Property<string>("Contexto")
                        .IsRequired();

                    b.Property<int?>("DinamicaId");

                    b.Property<string>("Metrica");

                    b.Property<string>("Motivo")
                        .IsRequired();

                    b.Property<string>("Observacao");

                    b.Property<string>("Participante")
                        .IsRequired();

                    b.Property<string>("Tempo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DinamicaId");

                    b.ToTable("Exemplos");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Fluxo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Fluxos");
                });

            modelBuilder.Entity("dinamicasAgile.Models.InformacoesBasicas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Duracao")
                        .IsRequired();

                    b.Property<string>("Material");

                    b.Property<string>("Proposito")
                        .IsRequired();

                    b.Property<string>("Titulo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("InformacoesBasicas");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Passo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<int?>("FluxoId");

                    b.HasKey("Id");

                    b.HasIndex("FluxoId");

                    b.ToTable("Passos");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Referencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<int?>("DinamicaId");

                    b.HasKey("Id");

                    b.HasIndex("DinamicaId");

                    b.ToTable("Referencias");
                });

            modelBuilder.Entity("dinamicasAgile.Models.TipoDinamica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("InformacoesBasicasId");

                    b.Property<string>("Tipo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("InformacoesBasicasId");

                    b.ToTable("TiposDinamicas");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Dinamica", b =>
                {
                    b.HasOne("dinamicasAgile.Models.Fluxo", "Fluxo")
                        .WithMany()
                        .HasForeignKey("FluxoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("dinamicasAgile.Models.InformacoesBasicas", "Resumo")
                        .WithMany()
                        .HasForeignKey("ResumoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("dinamicasAgile.Models.Exemplo", b =>
                {
                    b.HasOne("dinamicasAgile.Models.Dinamica")
                        .WithMany("Exemplos")
                        .HasForeignKey("DinamicaId");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Passo", b =>
                {
                    b.HasOne("dinamicasAgile.Models.Fluxo")
                        .WithMany("Passos")
                        .HasForeignKey("FluxoId");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Referencia", b =>
                {
                    b.HasOne("dinamicasAgile.Models.Dinamica")
                        .WithMany("Referencias")
                        .HasForeignKey("DinamicaId");
                });

            modelBuilder.Entity("dinamicasAgile.Models.TipoDinamica", b =>
                {
                    b.HasOne("dinamicasAgile.Models.InformacoesBasicas")
                        .WithMany("Tipos")
                        .HasForeignKey("InformacoesBasicasId");
                });
#pragma warning restore 612, 618
        }
    }
}
