// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dinamicasAgile.Banco;

namespace dinamicasAgile.Migrations
{
    [DbContext(typeof(DinamicaContext))]
    partial class DinamicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dinamicasAgile.Models.Dinamica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FluxoId");

                    b.Property<int?>("ResumoId");

                    b.HasKey("Id");

                    b.HasIndex("FluxoId");

                    b.HasIndex("ResumoId");

                    b.ToTable("Dinamicas");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Exemplo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avaliacao");

                    b.Property<string>("Contexto");

                    b.Property<int?>("DinamicaId");

                    b.Property<string>("Metrica");

                    b.Property<string>("Motivo");

                    b.Property<string>("Observacao");

                    b.Property<string>("Participante");

                    b.Property<string>("Tempo");

                    b.HasKey("Id");

                    b.HasIndex("DinamicaId");

                    b.ToTable("Exemplos");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Fluxo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Fluxos");
                });

            modelBuilder.Entity("dinamicasAgile.Models.InformacoesBasicas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Duracao");

                    b.Property<string>("Material");

                    b.Property<string>("Proposito");

                    b.Property<string>("Tipo");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.ToTable("InformacoesBasicas");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Passo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<int?>("FluxoId");

                    b.HasKey("Id");

                    b.HasIndex("FluxoId");

                    b.ToTable("Passos");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Referencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<int?>("DinamicaId");

                    b.HasKey("Id");

                    b.HasIndex("DinamicaId");

                    b.ToTable("Referencias");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Dinamica", b =>
                {
                    b.HasOne("dinamicasAgile.Models.Fluxo", "Fluxo")
                        .WithMany()
                        .HasForeignKey("FluxoId");

                    b.HasOne("dinamicasAgile.Models.InformacoesBasicas", "Resumo")
                        .WithMany()
                        .HasForeignKey("ResumoId");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Exemplo", b =>
                {
                    b.HasOne("dinamicasAgile.Models.Dinamica")
                        .WithMany("Exemplos")
                        .HasForeignKey("DinamicaId");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Passo", b =>
                {
                    b.HasOne("dinamicasAgile.Models.Fluxo")
                        .WithMany("Passos")
                        .HasForeignKey("FluxoId");
                });

            modelBuilder.Entity("dinamicasAgile.Models.Referencia", b =>
                {
                    b.HasOne("dinamicasAgile.Models.Dinamica")
                        .WithMany("Referencias")
                        .HasForeignKey("DinamicaId");
                });
#pragma warning restore 612, 618
        }
    }
}
